### ISSUE TITLE
Enum types for utils, etc?

### ISSUE THREAD

**Issue by joefiorini** [fxfactorial/bs-web3#1]
FWIW I had started my own implementation of web3 bindings, but eventually had to move on to something else because I couldn't get very far. It looks like you may already have something for most of this, but I thought I'd share in case you find the enum types (or anything else here) useful. Thanks for putting this together btw, I'm trying it out right now!

https://gist.github.com/joefiorini/dec5d8819b1b79456294bbdd5e783a57

**Comment by fxfactorial** [comment]
thanks, actually I think that bindings to web3 isn't a great use of time. The API is way bloated and I don't like it. I would recommend instead helping me here: https://github.com/fxfactorial/ethereum-re where we have code that compiles to JavaScript or Native!

**Comment by joefiorini** [comment]
Rockin, thanks! 🤘
